[project]
authors = ["Eric Ma <ericmajinglong@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "nll-ai.github.io"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
